#
# Author: Jonah Kubath
# Class: CS5541 Scheduling
#
SRC = ./CS5541_Scheduling_JonahKubath/src
BIN = ./CS5541_Scheduling_JonahKubath/bin

build:
	javac -d $(BIN) -cp $(SRC) CS5541_Scheduling_JonahKubath/src/scheduling_JonahKubath/*.java

use:
	java -cp $(BIN) scheduling_JonahKubath/Main